export const CHANGE_PRODUCT = 'CHANGE_PRODUCT';
export const SET_PRODUCT = 'SET_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

export default {
    CHANGE_PRODUCT,
    SET_PRODUCT,
    DELETE_PRODUCT,
}